### ISSUE TITLE
UnsubscribeWayPoints: Behavior in case HMI responds with unexpected successful result code

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_requirements#35]
Currently SDL has requirement:

> In general HMI is expected to respond with the result codes that comply with the API and in case of occurrence of the response that is not listed in HMI obviously it's a bug on HMI side. BUT in such situation SDL should behave the same way as in case of "any unknown issue" and respond with GENERIC_ERROR, success:false to mobile app 

Please clarify the following use case:
App->SDL: SubscribeWayPoints(valid params)
SDL->HMI: Navigation.SubscribeWayPoints(params)
HMI->SDL: respond with unexpected successful result code (e.g.: WARNINGS, RETRY, SAVED etc.)
SDL->App response with GENERIC_ERROR, success:false

Questions:
1) Is requirement above applicable for SubscribeWayPoints RPCs?
2) If requirement is applicable should SDL subscribe internally to get changes on way points (OnWayPointChange) since result code from HMI is successful?
3) If the answer on previous question is "No" HMI thinks that it's subscribed (it answered with success code) and therefore will send OnWayPointChange notifications to SDL. But SDL will filter them since internally it's unsubscribed. Is this correct behavior?
4) If the answer on 2nd question is "Yes" Mobile application thinks that it's unsubscribed (it got GENERIC_ERROR). But SDL will transfer OnWayPointChange notifications to it (since SDL thinks it's subscribed) 
5) What is correct behavior for UnsubscribeWayPoints RPC?

**Comment by KhrystynaDubovyk** [comment]
@robinmk, please help to clarify the issue

**Comment by AStasiuk** [comment]
@robinmk, any updates on this?

**Comment by robinmk** [comment]
Since SDL is aware that HMI successfully subscribed, I would say that SDL should send a "SUCCESS" response back to the app . That way every component will be in sync.
Ideally, HMI must not provide an unexpected result code and such items should be logged as issues with HMI.
@JackLivio , do you agree on the above?

**Comment by mrapitis** [comment]
We should avoid adding too much compensating code for an HMI side bug -- especially for things like filtering out notifications  (in a correct implementation this should not happen).  I also agree the app should receive the SUCCESS response.  SDL could also log a warning that the result code did not meet expectations.

**Comment by robinmk** [comment]
@AStasiuk @KhrystynaDubovyk 

After discussing with Jack and Zhimin, we concluded that:
i). HMI should not provide an unexpected result codes and such occurrences should be logged as issues against the HMI.
ii) In case HMI does send an unexpected result code, since SDL Core will not be able to confirm if that result code meant a successful subscription or unsucessful subscription from HMI, SDL Core should provide a response of GENERIC_ERROR.

During our discussion, we noticed that in the HMI API.xml the resultCodes although defined by the `Result` enum are not used at the individual RPC level. This may be a separate issue and we will follow up separately on it.

**Comment by LuxoftAKutsan** [comment]
@robinmk @mrapitis 

This is the gap in requirements clarifications.
The individual result code is a good feature for mobile developers to reduce the count of possible reactions on HU response.
But there should be either same requirements for HMI or there should be requirements for SDL how to negotiate result codes from HMI.

Also please note that behavior that you suggested : 
```
i). HMI should not provide an unexpected result codes and such occurrences should be logged as issues against the HMI.
ii) In case HMI does send an unexpected result code since SDL Core will not be able to confirm if that result code meant a successful subscription or unsuccessful subscription from HMI, SDL Core should provide a response of GENERIC_ERROR.
```
is completely new functionality for SDL. 
First of All, any result code is expected from HMI. According to HMI API, there are no responses that HMI can't send to some certain RPC. 
So list of not expected HMI result codes should be mentioned in guidelines for each HMI response.
Or this list can be part of API XML same as for mobile API. 
Anyway, this should be done within the proposal. We can prepare such proposal for SDL

**Comment by KhrystynaDubovyk** [comment]
To sum up, 

1. **The answer to the initial question is:**

In case HMI responds SDL with an unexpected result code 
SDL must 
respond GENERIC_ERROR, success:false to mobile app  

2. The applicable HMI result codes described in either HMI_API.xml or(and) HMI_Guidelines is the subject of the separate issue.

@robinmk,  please confirm

**Comment by robinmk** [comment]
yes

**Comment by KhrystynaDubovyk** [comment]
Please,  see the proposal created [HMI result codes usage at the individual RPC level](https://github.com/KhrystynaDubovyk/sdl_evolution/blob/hmi_api_resultCodes/proposals/NNNN-HMI_API_resultCodes_processing.md)
