### ISSUE TITLE
Criteria of invalid response from HMI 

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_requirements#36]
@robinmk, we have [a use case](https://github.com/smartdevicelink/sdl_requirements/blob/master/detailed_docs/embedded_navi/Get%20Destination_and_Waypoints.md) 

> Exception 6:
> 
> 7.2.a Response from HMI is invalid
> 
> 7.2.b SDL responds GENERIC_ERROR, success:false to mobile application

**To be on the same page, please confirm following criteria of _invalid response_ from HMI** 

a. params out of bounds
b. mandatory params are missing
c. params of wrong type
d. invalid json
Note: in case SDL cannot parse 'method_name' from json then SDL must respond to mobile app GENERIC_ERROR, info: "'%component-name%' component does not respond"
e. incorrect combination of params

**Comment by AStasiuk** [comment]
@robinmk, any updates on this question?

**Comment by robinmk** [comment]
These criteria are correct.

**Comment by mrapitis** [comment]
I agree, the expectation provided here looks accurate.  Can we also confirm that other RPC's generally behave in the same way (not just waypoint based rpc's)?

**Comment by JackLivio** [comment]
I agree this criteria looks good to me.

**Comment by KhrystynaDubovyk** [comment]
@mrapitis, for now this requirement will be implemented for waypoint based RPCs in terms of [Last Mile Navigation proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0003-last-mile-navigation.md)
Implementation of this requirement for other RPC's will be done in terms of [issues/1874](https://github.com/SmartDeviceLink/sdl_core/issues/1874)
