### ISSUE TITLE
[RC:OnRCStatus]  Should OnRCStatusNotification contain module data for each module or only module type

### ISSUE THREAD

**Issue by LuxoftAKutsan** [smartdevicelink/sdl_requirements#45]
Proposal : https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0106-remote-control-onRcStatus-notification.md 

According to API OnRCStatusNotification should contain *allocatedModules* and *freeModules* as Module Data:
```xml
<param name="allocatedModules" type="ModuleData" minsize="0" maxsize="100" array="true" mandatory="true">
    <description>Contains a list (zero or more) of module types that are allocated to the application.</description>
  </param>
  <param name="freeModules" type="ModuleData" minsize="0" maxsize="100" array="true" mandatory="true">
    <description>Contains a list (zero or more) of module types that are free to access for the application.</description>
  </param>    
```

But in description specified that is should contain a list of module types.
Module data is able to keep also ModuleData for each module 
```xml
   <struct name="ModuleData">
        <description>The moduleType indicates which type of data should be changed and identifies which data object exists in this struct. For example, if the moduleType is CLIMATE then a "climateControlData" should exist</description>
        <param name="moduleType" type="ModuleType" mandatory="true">
        </param>
        <param name="radioControlData" type="RadioControlData" mandatory="false">
        </param>
        <param name="climateControlData" type="ClimateControlData" mandatory="false">
        </param>
        ...
 </struct>
```
All data paremeters are not mandatory, should OnRCStatusNotification request module data for each module type from HMI and Send it in OnRCStatusNotification? Or it should specify only moduleType in OnRCStatusNotification?

**Comment by LuxoftAKutsan** [comment]
We suppose thatOnRCStatusNotification should specify only module type in OnRCStatusNotification.
And in that case I would suggest to change OnRCStatusNotification API to folowing:

```xml
    <function name="OnRCStatus" functionID="OnRCStatusID" messagetype="notification">
      <description>Issued by SDL to notify the application about remote control status change on SDL</description>
      <param name="allocatedModules" type="ModuleType" minsize="0" maxsize="100" array="true" mandatory="true">
        <description>Contains a list (zero or more) of module types that are allocated to the application.</description>
      </param>
      <param name="freeModules" type="ModuleType" minsize="0" maxsize="100" array="true" mandatory="true">
        <description>Contains a list (zero or more) of module types that are free to access for the application.</description>
      </param>
    </function>
```

**Comment by KhrystynaDubovyk** [comment]
@yang1070, what is your assumption?

**Comment by yang1070** [comment]
@KhrystynaDubovyk  In OnRCStatusNotification, it is a list of ModuleData, each ModuleData shall only contain a moduleType, there shall be no xxxxControlData in the ModuleData struct in the notification.

The original design was to just use a list of moduleTypes/modules. Livo's suggestion was to use ModuleData. the consideration is in the future we may have a mechanism  to identify a module (for example, the zone id, or UUID of a module), then we don't need a change for OnRCStatusNotification, just a change for ModuleData. 

Sorry, the description is not updated.
