### ISSUE TITLE
[SDL-RC] - GetInteriorVehicleData

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_requirements#48]
Issue: https://github.com/SmartDeviceLink/sdl_core/issues/1798

According to API: https://github.com/yang1070/sdl_core/blob/newRCModule/src/components/interfaces/MOBILE_API.xml#L6367
```
<function name="GetInteriorVehicleData" messagetype="request">
    ...
  <param name="subscribe" type="Boolean" mandatory="false" defvalue="false">
    <description>If subscribe is true, the head unit will send onInteriorVehicleData notifications for the module type</description>
    ...
</function>
```
_GetInteriorVehicleData request_  has optional parameter "subscribe" with default value : _false_. 

But in case when mobile applications use GetInteriorVehicleData RPC to read the current status value of remote-control module, (_send GetInteriorVehicleData **without** parameter subscribe_), according to API, SDL receives this parameter with value _false_, which means that application wants to unsubscribe the module's data change notification, which is incorrect.

We propose to delete default value for parameter subscribe from MOBILE and HMI API's, 
@yang1070 do you agree with it?

**Comment by yang1070** [comment]
@LitvinenkoIra If the parameter `subscribe` is not present in the RPC `GetInteriorVehicleData` request, that means SDL does not change the subscription status. 
If the parameter `subscribe` is in the RPC `GetInteriorVehicleData` request, SDL shall do proper action according to the value true/false. true means to subscribe, false mean to un-subscribe.

I agree there shall be no default value for this parameter.

**Comment by LitvinenkoIra** [comment]
@yang1070 OK, thanks.
