### ISSUE TITLE
SDL behavior in case unable to get system time from HMI

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_requirements#52]
Question is related to proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0120-GetSystemTime.md.

According to proposal security service will be started only in case HMI provided system time.

And what about case when HMI can not provide system time, e.g navigation module is unavailable, satellites are not available( vehicle is some where in tunnel, on underground parking ).
Is this okay that application will not be able to start secure service?
Must SDL start unsecure service or fail handshake with session start in case application can not start secure service because of absence system time?

**Comment by GetmanetsIrina** [comment]
@dboltovskyi, @AByzhynar , @KhrystynaDubovyk , please be informed about question.

**Comment by mrapitis** [comment]
@GetmanetsIrina 
The handshake process will need to be postponed until receiving a corresponding notification from hmi.

**Comment by GetmanetsIrina** [comment]
@mrapitis, thanks, but what if hmi does not send corresponding notification at all by some unexpected reason?

**Comment by mrapitis** [comment]
@GetmanetsIrina in that case SDL must fail the handshake process.

**Comment by GetmanetsIrina** [comment]
@mrapitis , Thank you!
