### ISSUE TITLE
Clarification expected results in cases with READ_ONLY code for SetInteriorVehicleData(LIGHT)

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_requirements#73]
Question is related to proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0165-rc-lights-more-names-and-status-values.md

#### Please clarify expected result in the next case:
**In case**
1. `LightCapabilities` value is set with `statusAvailable = true` by `RC.GetCapabilities`
2. Mobile app requests `SetInteriorVehicleData` with LightName_1 and LightName_2, LightStatus = `"RAMP_UP"/"RAMP_DOWN"/"UNKNOWN"/ "INVALID"` for LightName_1 and with LightStatus= `"ON"` for LightName_2

**Expected result:**
**1.** SDL processes request successful with only settable parameter LightName_2
**2.** SDL rejects the request with result code `READ_ONLY`, and info="The LightStatus enum passed is `READ ONLY` and cannot be written."

#### Also please confirm expected result in case 
1. `LightCapabilities` value is set with `statusAvailable = true` by `RC.GetCapabilities`
2. Mobile app requests `SetInteriorVehicleData` with LightName_1 and LightStatus = `"ON"` and current LightStatus  for LightName_1 on HMI is `"RAMP_UP"/"RAMP_DOWN"/"UNKNOWN"/ "INVALID"`

**Expected result:**
SDL resends request to HMI and HMI handles this situation - responds with resultCode `READ_ONLY`

**Comment by GetmanetsIrina** [comment]
@KhrystynaDubovyk , please be informed about question.

**Comment by yang1070** [comment]
@GetmanetsIrina 
the expected result is case 1
2. SDL rejects the request with result code READ_ONLY, and info="The LightStatus enum passed is READ ONLY and cannot be written."

Expected result for case 2
SDL shall not responds with resultCode `READ_ONLY`, as  LightStatus = "ON" is not a read only value
SDL shall forward request to HMI and HMI handles this situation.

**Comment by GetmanetsIrina** [comment]
@yang1070, thanks!
