### ISSUE TITLE
Clarification of the expected result in cases mobile app requests changes for hdRadioEnable, but capabilities do not allow

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_requirements#78]
Question is related to proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0160-rc-radio-parameter-update.md

**Please clarify the expected result in the next case:
In case:**
1) SDL receives hdRadioEnableAvailable = false/siriusxmRadioAvailable = false/without hdRadioEnableAvailable/without siriusxmRadioAvailable in RC.GetCapabilities from HMI
2) Mobile app requests SetInteriorVehicleData with changing ("hdRadioEnable": ON/"band": "XM").

**Expected result:**
1. SDL resends request to HMI and HMI responds with resultCode READ_ONLY

or

2. SDL rejects request with resultCode READ_ONLY and does not send request to HMI

**Comment by GetmanetsIrina** [comment]
@KhrystynaDubovyk , please be informed about issue

**Comment by HSavynetska** [comment]
@KhrystynaDubovyk  , please be informed about issue.

**Comment by GetmanetsIrina** [comment]
Closed by mistake.

**Comment by yang1070** [comment]
@HSavynetska @GetmanetsIrina @KhrystynaDubovyk 
I think in this case ```Mobile app requests SetInteriorVehicleData with changing ("hdRadioEnable": ON/"band": "XM").```, where `hdRadioEnable` is not a supported capability and `band` is supported and is not read-only, so SDL rejects request with resultCode `UNSUPPORTED_RESOURCE` and does not send request to HMI.

And this is consistent with the behavior when the request fails the  `CheckIfModuleDataExistInCapabilities` check.

**Comment by GetmanetsIrina** [comment]
@yang1070 , thanks!
