### ISSUE TITLE
Expected results in cases hdRadioEnable is not active.

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_requirements#82]
Question is related to proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0160-rc-radio-parameter-update.md

**Please confirm the expected result in the next cases:**

#### Case 1
**Precondition** 
On the HMI `hdRadioEnable` is not activated.

**In case:** 
1) Mobile app sends request `SetInteriorVehicleData` with params:
`"hdChannel": 2`

**Observed behavior**
Successful processing `SetInteriorVehicleData`.
To the HMI changed the parameter `"hdChannel": 2`

#### Case 2
 **Precondition** 
Mobile application sends `GetInteriorVehicleData` with `moduleType= RADIO`, `Subscribe = ON`.
On the HMI `hdRadioEnable` is not activated.

**In case:** 
1) On the HMI are params update:
`"hdChannel": 7`
`"availableHDs":7`

**Observed behavior**
Mobile app  receive `OnInteriorVehicleData` with updated params `("hdChannel": 7, "availableHDs":7)`

**Comment by GetmanetsIrina** [comment]
@KhrystynaDubovyk , please be informed about issue.

**Comment by yang1070** [comment]
@ HSavynetska @GetmanetsIrina 
In case 2, if `hdRadioEnable` is not activated on HMI, HMI will not get information about `availableHDs` and current `hdChannel`, so HMI shall not allow user/tester to change the value of `availableHDs`  and `hdChannel`, and shall not include these two parameters in the  `OnInteriorVehicleData` and the response of `Get/SetInteriorVehicleData`. Probably there is no `OnInteriorVehicleData` notification if there is nothing else changes.

In case 1, Mobile app sends request `SetInteriorVehicleData` with params: `"hdChannel": 2` and On the HMI `hdRadioEnable` is not activate, HMI shall give a failure response in two sub-cases. 

If `hdChannelAvailable` is `true` in remote control capability and `hdRadioEnable` is not activated on HMI, HMI responds with `info` as `HD radio is not turned on` and I'm not sure about the `result_code`, probably `UNSUPPORTED_RESOURCE` or `DATA_NOT_AVAILABLE` or `REJECTED`  . 

If `hdChannelAvailable` is `false` in remote control capability, probably SDL already rejects the request, if not and SDL forwards it to HMI, HMI responds with `result_code` `UNSUPPORTED_RESOURCE` and `info` `This vehicle does not support the requested resource`(HD radio).

**Comment by LitvinenkoIra** [comment]
@yang1070 
and lets confirm that :
If hdChannelAvailable is true in remote control capability and hdRadioEnable is not activated on HMI, HMI responds with info as `HD radio is not turned on` and result_code will be **`UNSUPPORTED_RESOURCE`**

**Comment by yang1070** [comment]
@LitvinenkoIra 
```
and lets confirm that :
If hdChannelAvailable is true in remote control capability and hdRadioEnable is not activated on HMI, 
HMI responds with info as HD radio is not turned on and result_code will be UNSUPPORTED_RESOURCE
```
confirmed
