### ISSUE TITLE
Conditions for sending OnRCStatus with allowed parameter

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_requirements#84]
Question is related to proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0172-onRcStatus-allowed.md.

As `allowed` parameter is not mandatory, so conditions for it sending must be specified.

**Please confirm the next:**
SDL must sends `allowed` parameter with corresponding value in case of changing allowed/disallowed RC status on HMI.
SDL does not sends `allowed` parameter by module allocation/deallocation.

**Also i have one question** - In case RC functionality is disallowed on HMI and RC application starts registration, should SDL sends OnRCStatus(allowed = false, allocatedModules = [], freeModules = []) to new registered application?

According to current implementation in case of functionality RC is not allowed not a single notification are sent to mobile apps.

In case answer to the question is 'yes', so app registration is also triger to send `allowed` parameter.

**Comment by GetmanetsIrina** [comment]
@KhrystynaDubovyk , please be informed about question.

**Comment by yang1070** [comment]
@GetmanetsIrina @KhrystynaDubovyk
The answer is yes for all questions.

**Comment by GetmanetsIrina** [comment]
@yang1070 , thanks!
