### ISSUE TITLE
GetInteriorVehicleData(subscribe = false) by app unregistration

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_requirements#87]
Question is related to proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0178-GetInteriorVehicleData.md.

Should SDL unsubscribe InteriorVehicleData with requests to HMI by app unregistration?

In case 'Yes' for 1st question - Should rules for InteriorVehicleData unsubscribtion be applied for app unregistration?

**Comment by GetmanetsIrina** [comment]
@KhrystynaDubovyk , @LuxoftAKutsan, please be informed about question.

**Comment by yang1070** [comment]
@GetmanetsIrina, @KhrystynaDubovyk , @LuxoftAKutsan, 
That's a very good question. Thank you @GetmanetsIrina for catching this. The answer is Yes. 
SDL shall unsubscribe InteriorVehicleData if there is no applications subscribe to a module. app un-registration event and other events like lost connection, may cause the number of apps that subscribe to a module down to 0.

**Comment by yang1070** [comment]
@GetmanetsIrina, Regarding the question `Should rules for InteriorVehicleData unsubscribtion be applied for app unregistration?`, what are the rules?

**Comment by GetmanetsIrina** [comment]
@yang1070 , rule is the the last app subscribed to module_1 is unregister SDL must send GetInteriorVD(subscribe=false), SDL will not send GetInteriorVD(subscribe=false) by app unregistration (has subscription for module_1) in case some other app is still has subscription for module_1.

**Comment by yang1070** [comment]
@GetmanetsIrina, understood
