### ISSUE TITLE
Limitation for GetInteriorVehicleDataRequest

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_requirements#88]
Issue is related to proposal: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0178-GetInteriorVehicleData.md

Please confirm the next behavior:
.ini file contains the next setting 
```
; Limitation for a number of GetInteriorVehicleDataRequest requests (the 1st value) per (the 2nd value) seconds
+GetInteriorVehicleDataRequest = x, y
```
1. In case mobile application has no subscriptions for module_1 (_SDL must resend GetInteriorVehicleData requests to HMI_) and mobile app starts send GetInteriorVehicleData(module_1, without subscribe parameter) , SDL receives `x` number of GetInteriorVehicleData requests per `y` and starts reject `x+1`GetInteriorVehicleData requests with result code "REJECTED" until `y` time is not expired.

2. If mobile application has subscriptions for module_1 _(SDL must not resend GetInteriorVehicleData requests to HMI_)  and starts send GetInteriorVehicleData(module_1) , limitation for GetInteriorVehicleData request  is not applied.

3. In case there are 2 registered mobile apps have no subscriptions for module_1(_SDL must resend GetInteriorVehicleData requests to HMI_) and mobile apps start send GetInteriorVehicleData(module_1, without subscribe parameter) requests at the same time, SDL receives `x` number of GetInteriorVehicleData requests without relating to any app per `y` and starts reject `x+1`GetInteriorVehicleData requests with result code "REJECTED" from both apps until `y` time is not expired.

**Comment by GetmanetsIrina** [comment]
@KhrystynaDubovyk , please be informed about clarification.

**Comment by yang1070** [comment]
@GetmanetsIrina 1 and 2 look good to me. However, the forwarding of a `GetInteriorVehicleData` request depends on the availability of the module_1's  cache. Depending on implementation, it may or may not be the same as any app subscribed to module_1 (remember cache is created after receiving a successful response result, the timing issue). 

In 3, The counting of the number of GetInteriorVehicleData requests is regardless of the mobile apps.

**Comment by yang1070** [comment]
@GetmanetsIrina It looks that in your writing, the counting is per module_1, that is good for me too.
