### ISSUE TITLE
When app wants to set audio source directly to XM, should SDL check availability of sirius XM radio?

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_requirements#96]
in proposal: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0182-audio-source-am-fm-xm.md

When app wants to set audio source directly to XM, should SDL check availability of sirius XM radio?
Because now we do not have the corresponding fields in AudioControlCapabilities for new audio sources (AM, FM, XM). 

We have param for XM radio (siriusxmRadioAvailable) in RadioControlCapabilities, that was added in proposal number 0160 (https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0160-rc-radio-parameter-update.md) 
But in original proposal:

>  This proposal is an update to a proposal that has not been implemented but is slated for the next release of projects. The proposal is number 0099.

Should we add some new params to AudioControlCapabilities?
something like 
```
                "audioControlCapabilities": [
                {
                        "moduleName": "audio",
                        "sourcesAvailable": [ "AM, FM, XM, DAB" ], // instead of "sourceAvailable": true
                        "volumeAvailable": true,
                        "equalizerAvailable": true,
                        "keepContextAvailable" : true,
                        "equalizerMaxChannelId": 10

                    }
                ]
```

Or base the implementation of 0182 on 0160 and check AudioControlCapabilities and RadioControlCapabilities also in case when app wants to set audio source directly to XM?

Or is it the responsibility of the HMI to check whether the audio source can be installed? (in case when "sourceAvailable": true in capabilities)

**Comment by LitvinenkoIra** [comment]
@yang1070 and should we add "DAB" to RadioBand enum?

**Comment by yang1070** [comment]
@LitvinenkoIra 
For now, we don't add any new parameters.  sdl just pass the request to HMI, HMI will reject the request if the vehicle does not support XM or DAB radio. SDL HMI implementation can just not support DAB. Your suggestion to change `sourceAvailable` from Boolean to  supported audio source string list is very good.  We will consider it, If we choose this option, we need a new proposal for it. I like the idea that SDL check the capability.

**Comment by LitvinenkoIra** [comment]
@yang1070 Got it. Thanks for your response.
